# Generated by Django 6.0.5 on 2026-05-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
